// <auto-generated />
using System;
using CarWashStation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarWashStation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarWashStation.Models.BlockedSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("BlockedSlots");
                });

            modelBuilder.Entity("CarWashStation.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarPlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CarWashStation.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Professionell yttre rengöring",
                            Name = "Utvändig tvätt",
                            Price = 400m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Komplett rengöring för både insida och utsida",
                            Name = "In & utvändig tvätt",
                            Price = 750m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Djupgående rengöring och polering",
                            Name = "Rekond",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kombination av rengöring och skyddande vaxlager",
                            Name = "Tvätt + vax",
                            Price = 1750m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rengöring av motorrummet",
                            Name = "Motortvätt",
                            Price = 350m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grundlig dammsugning och avtorkning",
                            Name = "Invändig tvätt",
                            Price = 400m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Bekväm säsongsförvaring inklusive skifte",
                            Name = "Däckförvaring + skifte",
                            Price = 950m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Snabb och säker byte av hjul",
                            Name = "Däckskifte",
                            Price = 350m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Långvarigt skydd mot repor och UV-ljus",
                            Name = "Lackförsegling",
                            Price = 2295m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Professionell reparation av däckskador",
                            Name = "Laga punktering",
                            Price = 350m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Montering på fälg och balansering",
                            Name = "Däckmontering",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("CarWashStation.Models.Booking", b =>
                {
                    b.HasOne("CarWashStation.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
